pipeline {
    agent any
    tools { 
        maven '3.8.1' 
    }
    environment { 
        buildid = "${env.BUILD_ID}"
        buildnumber = "${env.BUILD_NUMBER}"
        buildtag = "${env.BUILD_TAG}"
        COMMON_CREDS = credentials('NEXUS_COMMON_CREDS')
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Publish JAR') {
            steps {
                // Publish the generated JAR file
                // You can specify the path to your JAR file based on your Maven project structure
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true

                withCredentials([usernamePassword(credentialsId: '${COMMON_CREDS}', usernameVariable: '${COMMON_CREDS_USR}', passwordVariable: '${COMMON_CREDS_PSW}')]) {
                    // Upload JAR file to Nexus repository
                    nexusPublisher nexusInstanceId: 'nexus', nexusRepositoryId: 'mvn-andy', packages: [nexusMavenArtifact(
                        groupId: 'com.mycompany.app',
                        version: '1.0.0',
                        repositoryName: 'mvn-andy',
                        artifact: [
                            classifier: '',
                            extension: 'jar',
                            file: 'target/*.jar'
                        ]
                    )]
                }
            }
        }
    }
}
